### ISSUE TITLE
객체지향을 설명하는 예제 만들기

### ISSUE THREAD

**Issue by joshuakimDwan** [SundayBird/project#11]
- 객체지향 5대 원칙(SOLID) 중 하나 이상을 설명하는 예제를 원하는 방식대로 만들어오면 됩니다.
    -  참고: https://wkdtjsgur100.github.io/solid-principle/

**Comment by kyunooh** [comment]
https://github.com/kyunooh/solid

**Comment by EJSohn** [comment]
리스코프 치환 법칙 (LSP) 
- 예제: 몬스터 캐릭터는 전부 좋아해 포켓몬은 좋아하지만 또가스는 싫어하는 아이.
- 궁금: [link](https://vandbt.tistory.com/41)에서 `하지만, 부모인 Rectangle 객체에서 작동하는 행위가 Square 객체에 대해서 작동하지 않는다는 것은 LSP를 위반하는 것이고, 파생클래스 행위의 내부 상세를 안다는 것은 OCP open-close principle 또한 위반 하는 것입니다. `의 의미
